sudo: false
language: cpp

addons:
  apt:
    packages:
      - libboost-all-dev
      #- sdcc
    
env:
  global:
    - SDCC=3.3.0
    - SDCC_DIR=/tmp/sdcc-$SDCC

cache:
  directories:
    - $SDCC_DIR

before_install:
  - export PATH=$PATH:$SDCC_DIR/bin
  - chmod +x ./scripts/build-sdcc.sh

install:
  - ./scripts/build-sdcc.sh

before_script:
  - sdcc --version

script:
  - (cd ./firmware && make clean all)

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: 
    - ./firmware/build_by_sdcc/gpib-usbcdc.hex
    - ./firmware/build_by_sdcc/gpib-usbcdc.omf
  skip_cleanup: true
  all_branches: true  # https://github.com/travis-ci/travis-ci/issues/1675
  on:
    tags: true